-- Copyright (c) Microsoft Corporation. All rights reserved.
-- Licensed under the Apache 2.0 License.

import MachineGenerated.SymbolicTests

run_cmd do
  for theoremName in [
      ``Symbolic.Codec.decode_literal,
      ``Symbolic.Codec.equal_correct,
      ``Symbolic.enumDecode_encode,
      ``Symbolic.enumEncode_decode,
      ``Symbolic.vectorGet_ofFn,
      ``Symbolic.vectorOfFn_get,
      ``Symbolic.matchSum_correct,
      ``Symbolic.tableExpr_correct,
      ``Symbolic.tableGet_correct,
      ``Symbolic.tableStore_correct,
      ``Symbolic.tableMember_correct,
      ``Symbolic.tableAll_correct,
      ``Symbolic.finValue_correct,
      ``Symbolic.tableSelect_correct,
      ``Symbolic.Codec.tableSelect_correct,
      ``Symbolic.setMember_correct,
      ``Symbolic.setInsert_correct,
      ``Symbolic.setErase_correct,
      ``Symbolic.optionalTest_correct,
      ``Symbolic.Expr.normalize_correct,
      ``Symbolic.Container.select_correct,
      ``Symbolic.Container.store_correct,
      ``Symbolic.Container.take_correct,
      ``Symbolic.Container.drop_correct,
      ``Symbolic.Container.append_correct,
      ``Symbolic.Container.membership_correct,
      ``Symbolic.Container.input_correct,
      ``Symbolic.Container.input_length,
      ``Symbolic.Container.foldr_correct,
      ``Symbolic.Container.map_correct,
      ``Symbolic.Container.all_correct,
      ``Symbolic.Container.boundedAll_correct,
      ``Symbolic.Container.filter_correct,
      ``Symbolic.Container.enqueueNoDup_correct,
      ``Symbolic.Container.prefixEqual_correct,
      ``Symbolic.Container.removeFirst_correct,
      ``Symbolic.Container.noDup_correct,
      ``Symbolic.Container.takeFirst_correct,
      ``Symbolic.fresh_fits,
      ``Symbolic.fresh_realizes,
      ``Symbolic.realizes_congr,
      ``Symbolic.realizes_exists,
      ``Symbolic.fresh_surjective,
      ``Symbolic.allocate_run,
      ``CCFRaft.SymbolicModel.entry_equal_correct,
      ``CCFRaft.SymbolicModel.message_equal_correct,
      ``CCFRaft.SymbolicModel.freshEntry_fits,
      ``CCFRaft.SymbolicModel.freshEntry_complete,
      ``CCFRaft.SymbolicModel.evalEntry_node?,
      ``CCFRaft.SymbolicModel.evalEntry_bounds_iff,
      ``CCFRaft.SymbolicModel.messageSource_correct,
      ``CCFRaft.SymbolicModel.logSlice_correct,
      ``CCFRaft.SymbolicModel.queueEnqueue_correct,
      ``CCFRaft.SymbolicModel.logPrefixEqual_correct,
      ``CCFRaft.SymbolicModel.queueTakeFirst_correct,
      ``CCFRaft.SymbolicModel.entryWithin_correct,
      ``CCFRaft.SymbolicModel.logWithin_correct,
      ``CCFRaft.SymbolicModel.messageWithin_correct,
      ``CCFRaft.SymbolicModel.queueWithin_correct,
      ``CCFRaft.SymbolicModel.optionalIndexWithin_correct,
      ``CCFRaft.SymbolicModel.indicesWithin_correct,
      ``CCFRaft.SymbolicModel.localWithin_correct,
      ``CCFRaft.SymbolicModel.optionalLocalWithin_correct,
      ``CCFRaft.SymbolicModel.nodeTableAll_correct,
      ``CCFRaft.SymbolicModel.stateWithin_correct,
      ``CCFRaft.SymbolicModel.messageDestination_correct,
      ``CCFRaft.SymbolicModel.messageTerm_correct,
      ``CCFRaft.SymbolicModel.observe_correct,
      ``CCFRaft.SymbolicModel.appendRequestMatches_correct,
      ``CCFRaft.SymbolicModel.firstFromMatches_correct,
      ``CCFRaft.SymbolicModel.entryQueue_correct] do
    for axiomName in ← Lean.collectAxioms theoremName do
      unless axiomName == ``propext || axiomName == ``Classical.choice ||
          axiomName == ``Quot.sound do
        throwError "{theoremName} depends on unapproved axiom {axiomName}"
