-- Copyright (c) Microsoft Corporation. All rights reserved.
-- Licensed under the Apache 2.0 License.

import MachineGenerated.SymbolicTransitionTests
import MachineGenerated.SymbolicTransitionAdapter
import MachineGenerated.SymbolicTransitionCompletenessTests
import MachineGenerated.SymbolicTransitionNormalizeTests
import MachineGenerated.SymbolicTransitionEvaluationTests

open CCFRaft.SymbolicTransition

run_cmd do
  for name in [
      ``decode_choose, ``setUnion_correct, ``setIntersection_correct, ``setDifference_correct,
      ``setCard_correct, ``majority_correct, ``foldl_correct, ``foldrFrom_correct,
      ``appendSequence_correct,
      ``configurationStep_correct, ``configurationsFrom_correct,
      ``signatureAfterStep_correct, ``signatureAfter_correct,
      ``retiredIndexStep_correct, ``retiredIndex_correct,
      ``configurations_length, ``configurationList_bound,
      ``allConfigurationExpr_correct, ``allConfigurationExpr_bound,
      ``latestConfigurationExpr_correct, ``currentConfigurationStep_correct,
      ``currentConfigurationExpr_correct, ``filter_decode,
      ``activeConfigurationExpr_correct, ``activeNodeUnionExpr_correct,
      ``nodeSetContains_correct, ``retirementFrom_correct, ``retirementIndexExpr_correct,
      ``entryAtExpr_correct, ``signatureAtExpr_correct, ``termAtExpr_correct,
      ``rangeExpr_correct, ``maximumExpr_correct, ``committableStep_correct,
      ``maxCommittableExpr_correct, ``retiredEntryNodes_correct,
      ``committedRetiredStep_correct, ``committedRetiredNodesExpr_correct,
      ``isSome_value, ``filterIndexExpr_correct, ``signatureBindExpr_correct,
      ``membershipExpr_correct, ``setRetirementFields_correct, ``refreshRetirementExpr_correct,
      ``model_log_bound, ``readLocal_log_bound, ``refreshReadLocal_correct,
      ``filterNodeSet_correct, ``previouslyConfiguredStep_correct, ``previouslyConfiguredExpr_correct,
      ``retirementCompletedNodesExpr_correct, ``setCompletedData_correct, ``setCompletedExpr_decode,
      ``setCompletedExpr_correct, ``refreshCompletedExpr_correct,
      ``appendLocalEntry_correct, ``appendLocalEntry_log_bound, ``signatureLocal_correct,
      ``appendRefreshedLocal_correct, ``appendRefreshedLocal_log_bound, ``writeEntryNext_correct,
      ``signatureLocal_log_bound, ``localMembership_correct, ``signatureEnabled_correct,
      ``signatureNext_correct, ``signatureGuard_correct, ``signature_complete_model,
      ``pendingRetiredExpr_correct, ``retiredWriteContent_correct, ``retiredWriteLocal_correct,
      ``retiredWriteEnabled_correct, ``retiredWriteNext_correct, ``retiredWriteGuard_correct,
      ``retiredWrite_complete_model, ``submittedTransactionBound,
      ``clientTransactionBound_of_successorWithin, ``clientNext_outside_unrepresentable,
      ``submittedContains_correct, ``setSubmittedData_correct, ``setSubmittedExpr_correct,
      ``setInsert_image_correct, ``insertSubmitted_correct, ``clientLocal_correct,
      ``clientEnabled_correct, ``clientNext_correct, ``clientAccepted_correct,
      ``clientNext_bounded_correct, ``clientGuard_correct, ``client_complete_model,
      ``nodeTableExpr_correct, ``nodeTableGet_correct, ``nodeSetBit_correct,
      ``allocateSlotExpr_correct, ``allocateData_correct, ``allocateExpr_decode, ``allocateExpr_correct,
      ``setJoinedData_correct, ``setJoinedExpr_correct, ``setSentExpr_correct, ``setAddedSentExpr_correct,
      ``refreshRetirement_setSent, ``withAddedSent_refresh, ``intersection_empty_iff,
      ``configurationContent_correct, ``previousConfigurationExpr_correct, ``addedConfigurationExpr_correct,
      ``configurationLocal_correct, ``configurationLocal_log_bound, ``unjoinedAddedExpr_correct,
      ``configurationEnabled_correct, ``configurationNext_correct, ``configurationAccepted_correct,
      ``configuration_complete_model,
      ``boolAnd_true, ``boolOr_true, ``boolNot_true, ``all_decode, ``any_decode,
      ``localConfigurations_correct, ``localConfigurations_bound, ``localActiveNodes_correct,
      ``campaignExpr_correct, ``configurationMajorities_correct, ``readPreVote_correct,
      ``readCompleted_correct, ``campaignSupport_correct, ``nodeSingleton_correct,
      ``setElectionFields_correct, ``candidateLocal_correct, ``preCandidateLocal_correct,
      ``stepDownLocal_correct, ``candidateTransitionExpr_correct, ``timeoutEnabled_correct,
      ``preCandidateEnabled_correct, ``preMajorityExpr_correct, ``candidateEnabled_correct,
      ``candidateNext_correct, ``preCandidateNext_correct, ``timeoutAccepted_correct,
      ``preCandidateAccepted_correct, ``candidateAccepted_correct, ``eraseNode_correct,
      ``otherActiveExpr_correct, ``checkQuorumEnabled_correct, ``checkQuorumNext_correct,
      ``checkQuorumAccepted_correct,
      ``andLazy_correct, ``takeKnown_correct, ``takeCompact_correct,
      ``truncateLocal_correct, ``truncateLocal_log_bound, ``leaderFields_correct,
      ``leaderLocal_correct, ``leaderLocal_log_bound, ``leaderEnabled_correct,
      ``leaderNext_correct, ``leaderAccepted_correct, ``voteSendEnabled_correct,
      ``voteRequestFields_correct, ``voteSendMessage_correct, ``voteSendNext_correct,
      ``voteSendAccepted_correct,
      ``sentTo_correct, ``appendRequestFields_correct, ``appendSendMessage_correct,
      ``setSentTo_correct, ``appendSendEnabled_correct, ``appendSendNext_correct,
      ``appendSendAccepted_correct,
      ``matchedTo_correct, ``highestConfigurationStep_correct, ``highestConfigurationExpr_correct,
      ``allNodeSet_correct, ``rankComparison_correct, ``successorRank_correct,
      ``plausibleSuccessorExpr_correct, ``proposalEnabled_correct, ``proposalMessage_correct,
      ``proposalNext_correct, ``proposalAccepted_correct,
      ``replicationSupportExpr_correct, ``configuration_fold_contains, ``active_configuration_subset,
      ``replicationSupport_majority, ``hasMajorityAt_replicationSupport,
      ``natLt_true, ``acknowledgingExpr_correct, ``majorityAtExpr_correct,
      ``commitCandidateExpr_correct, ``commitScanStep_correct, ``highestCommitExpr_correct,
      ``setCommitExpr_correct, ``advancedLocal_correct, ``advancedLocal_log_bound,
      ``advanceStateExpr_correct, ``demoteExpr_correct, ``advanceNext_correct,
      ``terminalCommitExpr_correct, ``advanceReady_correct, ``advanceEnabled_correct,
      ``advanceAccepted_correct, ``advanceProposalEnabled_correct, ``advanceProposalNext_correct,
      ``advanceProposalAccepted_correct,
      ``dispatch_accepted_correct, ``dispatch_next_correct, ``adapter, ``verifiedEncoder,
      ``modelReceive, ``checkedEncoder, ``checkedEncoder_satisfiable_iff,
      ``decodeMemo_correct, ``evalEntryMemoM_correct, ``evalEntryMemo_correct, ``evaluateActionMemo_correct,
      ``importEntry_toData, ``withinBounds_fits, ``freshEntry_complete_model,
      ``decode_normalize, ``decode_normalizeMemo, ``evalEntry_normalize, ``evalEntry_normalizeMemo,
      ``compactCase_correct, ``optionCases_correct, ``isSome_correct,
      ``nodeTableSelect_correct, ``nodeTableStore_correct,
      ``entryNode_correct, ``allocated_correct, ``readLocal_correct, ``state_ext,
      ``writeLocalData_correct, ``writeLocal_decode, ``writeLocal_correct,
      ``queueTakeFirstById_correct,
      ``sourceAllowed_correct, ``newerMessage_correct, ``adoptTerm_correct,
      ``evalEntry_optionCases, ``updateTermEnabled_correct, ``updateTermNext_correct,
      ``updateTermGuard_correct, ``updateTerm_complete_model] do
    for axiomName in ← Lean.collectAxioms name do
      unless axiomName == ``propext || axiomName == ``Classical.choice ||
          axiomName == ``Quot.sound do
        throwError "{name} depends on unapproved axiom {axiomName}"
