name = "ccf-consistency"
version = "0.1.0"
defaultTargets = ["CCFConsistency"]

[[require]]
name = "veil"
git = "https://github.com/verse-lab/veil.git"
rev = "2ccca695fe62d2e488da8725a747972c2f115a61"

[[lean_lib]]
name = "CCFConsistency"
moreLeanArgs = [
    "-j",
    "4",
]
dynlibs = ["@cvc5/cvc5:shared"]
